#import "/local-lib/template-thesis.typ": *
#import "/metadata.typ": *
#pagebreak()
#heading(numbering:none)[#i18n("ack-title", lang:option.lang)] <sec:ack>

First of all, I want to thank my parents. For giving me the opportunity to study at such a great university, for their support every single time, for always believing in me when I didn't believe in myself - they always knew I would make it. They have always been my biggest role models in life, and everything I have now is because of them. I also want to thank my mom for being someone I can tell absolutely everything to - every secret, every worry, every thought. And I want to thank my dad for teaching me tennis when I was a child - that's what led me to become the head of the KSE Table Tennis Club and find amazing friends at university, who made these student years the best ones.

I want to thank my grandparents - they were always ready to help me with anything, and were even willing to learn how to code just to make things easier for me. Thank you for the fact that when I had classes until 9 PM, I could get to Akademmistechko in 20 minutes instead of an hour and a half, and thank you for always cooking so much and so well every time I came over, as if it was a wedding and not just my last class of the day. I want to thank my brother for always showing up - early or late - even though he wasn't a student here at that moment, just to help or support me.

I want to thank Veronika Anepska for absolutely everything - for always listening to me, for every party, every conversation, every idea, for believing in each other and supporting each other. Together we built discipline - not just opening TikTok every day to keep our streak alive, but also learning Italian every day, doing yoga every day, setting goals and reaching them together. I'm really happy that this diploma was made with you. I'm sure we have an amazing future ahead, because we're doing everything to make it happen.

I want to thank Bohdana Seheda for sitting next to me in an extra English class in first year and Maryna Chernetska for the fact that we were brought together in first year by the same problem - neither of us understood anything. Those small things helped me find such great friends.

Thank you to Ivan Suprun - for always being there to support me and after talking to you, everything always feels lighter. Thank you to Marko Hlibovytskyi for always telling me I would be fine when I felt like giving up, and for helping me install Windows when I needed it.

I really want to thank the EBD27 and BE27, and my Verkhovyna company. Thank you to Dariia Kozlova for the Integration parties, for Halloween vampires, and for inviting me in my fourth year to get through the hard winter moments and the power outages at Hotel Verkhovyna together. Thank you to Dmytro Shevchuk, Matvii Onyshchenko, Artem Litskevych, Dmytro Vasylchuk, Oleksandr Siryi - you are the best. Every holiday, every party, every memory with you is one of the best in my life. Thank you for every tennis game, every good lunch, every conversation, You are all absolute legends. Thank you to Oleh Skakun for always cheering me up and for driving me home, and for the two most interesting episodes in Master Chef.

Thank you to my friend from Italy, Gabriel, whom I met just before the full-scale invasion started - for helping me feel more confident, for every Eurovision night, for respecting my family and my country, and for the invitation to Italy. Thank you also to my friend from Spain, Markel - I'm sure we will meet someday too.

Thank you to Polina Mamchur, Sofiia Tyshchenko, Sofiia Krotova, Yaroslava Mala, Kateryna Shashkina and Matvii Talalaievskyi for every moment we went through together, for finding something positive even during the worst deadline weeks, and for always helping. And thank you to my table tennis team - for every training, every tournament, every victory.

I also want to thank Kateryna Pyvovarova for our conversation on the 5th floor of KSE - it was you who came up with the Soulmate feature idea, and I'm really glad that conversation happened.

I want to thank the teachers who left a real mark. Thank you to Taras Pavlov - he taught mathematics in the first year and managed to make difficult topics understandable, and more than that - he made me love them even more. Thank you to Yevhen Kubiuk for the practical sessions on algorithms and data structures: I did not miss a single class, because you rarely meet someone who loves what they do so genuinely and wants every student to truly understand. Thank you to Yaroslav Propoi for the practical product analytics course - it was after this course that I understood I want to build my life around analytics. Thank you to Vadym Yaremenko and Ihor Pysmennyi for their huge contribution to my knowledge. Thank you to Volodymyr Skochko - he returned my assignments with new comments every single time, and at some point I genuinely did not know when it would end. But at work I understood what he was preparing me for: clients are often unsatisfied, there are many rounds of revisions, and you just have to keep going. I am ready for that now. And a separate thank you for agreeing to help me install a virtual Windows on my Linux - even though it did not work out, what matters is that he did not say no and tried to help.

Thank you to academic director Artem Korotenko - over four years our leadership changed several times, and Artem inherited a situation that was not easy to walk into. He handles it well, and more importantly - you can always come to him with a question and get real help or at least honest advice. That is not something to take for granted.

And a very big thank you to my supervisor Denys Zavhorodnii. For every meeting, for the time spent reviewing my work, for the guidance, and for walking me through this entire process from start to finish. It was a real pleasure working with you.

Thank you to absolutely everyone who came into my life during these years and made it the best it could be - in such difficult times.